import io
import re
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH


class ReportGenerator:
    def create_word_report(self, title: str, messages: list[dict], charts: list[bytes] | None = None) -> bytes:
        """
        Generates a Word report from the chat history.

        Args:
            title (str): Report title
            messages (list): List of chat messages ({'role':, 'content':})
            charts (list): List of image bytes (optional)

        Returns:
            BytesIO: The Word document as a byte stream for download
        """
        doc = Document()

        # --- TITLE & HEADER ---
        heading = doc.add_heading(title, 0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph('Generated by DocuInsight').alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph('--- Document Analysis Report ---').alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_page_break()

        # --- CHAT CONTENT (with inline references per Q&A) ---
        for msg in messages:
            role = msg['role']
            content = msg['content']

            if role == "system" or not content:
                continue

            if role == "user":
                doc.add_heading('Question:', level=2)
                p_content = doc.add_paragraph(content)
                p_content.paragraph_format.space_after = Pt(12)

            elif role == "assistant":
                doc.add_heading('Analysis & Result:', level=2)

                ext = msg.get("extended_data", {})
                answer = ext.get("final_answer", "")
                refs = ext.get("references", [])

                # Renumber citations if extended_data is available
                display_content = content
                renumber = {}
                cited_raw = []
                if answer:
                    cited_raw = sorted(set(int(x) for x in re.findall(r'\[(\d+)\]', answer)))
                    renumber = {old: new for new, old in enumerate(cited_raw, start=1)}
                    if renumber:
                        display_content = re.sub(
                            r'\[(\d+)\]',
                            lambda m: f"[{renumber[int(m.group(1))]}]" if int(m.group(1)) in renumber else m.group(0),
                            display_content
                        )

                clean_content = display_content.replace("**", "").replace("### ", "")
                doc.add_paragraph(clean_content)

                # Inline references for this answer
                if refs:
                    doc.add_paragraph()  # spacing
                    p_ref_header = doc.add_paragraph()
                    run = p_ref_header.add_run('Sources:')
                    run.bold = True

                    seen_ids = set()
                    for ref in refs:
                        rid = ref.get('id')
                        # If we have cited_raw, filter to only cited sources
                        if cited_raw and rid not in cited_raw:
                            continue
                        if rid in seen_ids:
                            continue
                        seen_ids.add(rid)
                        display_id = renumber.get(rid, rid)
                        doc.add_paragraph(
                            f"[{display_id}] {ref.get('file', 'Unknown')} — Page {ref.get('page', '?')}",
                            style='List Bullet'
                        )

                doc.add_paragraph('_' * 40)

        # --- SAVE ---
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)

        return file_stream
